create table hotel.check_in (adicional_veiculo boolean not null, data_entrada timestamp(6) with time zone not null, data_saida timestamp(6) with time zone, hospede_id bigint not null, id bigint generated by default as identity, primary key (id));
create table hotel.hospede (valor_total_gasto numeric(38,2), valor_ultima_hospedagem numeric(38,2), data_cadastro timestamp(6) with time zone not null, id bigint generated by default as identity, documento varchar(255) not null unique, nome varchar(255) not null, telefone varchar(255) not null unique, primary key (id));
create table hotel.pagamento (valor_pago numeric(38,2), checkin_id bigint unique, data_pagamento timestamp(6) with time zone not null, hospede_id bigint not null, id bigint generated by default as identity, primary key (id));
alter table if exists hotel.check_in add constraint FKcsg6396ckmxgvt19hfu5m3a67 foreign key (hospede_id) references hotel.hospede;
alter table if exists hotel.pagamento add constraint FKb7vgnckdnkyq7y71bbemtg2u9 foreign key (checkin_id) references hotel.check_in;
alter table if exists hotel.pagamento add constraint FKhr5pe0vr0y5l67d6vy3uesjm6 foreign key (hospede_id) references hotel.hospede;
