-- V1__init.sql
-- Script inicial de criação das tabelas do sistema de hotelaria

CREATE SCHEMA IF NOT EXISTS hotel;

CREATE TABLE hotel.hospede (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  documento VARCHAR(255) NOT NULL UNIQUE,
  telefone VARCHAR(255) NOT NULL UNIQUE,
  data_cadastro TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  valor_total_gasto NUMERIC(38,2),
  valor_ultima_hospedagem NUMERIC(38,2)
);

CREATE TABLE hotel.check_in (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospede_id BIGINT NOT NULL,
  adicional_veiculo BOOLEAN NOT NULL,
  data_entrada TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  data_saida TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT fk_checkin_hospede
    FOREIGN KEY (hospede_id)
    REFERENCES hotel.hospede
);

CREATE TABLE hotel.pagamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospede_id BIGINT NOT NULL,
  checkin_id BIGINT UNIQUE,
  valor_pago NUMERIC(38,2),
  data_pagamento TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_pagamento_checkin
    FOREIGN KEY (checkin_id)
    REFERENCES hotel.check_in,
  CONSTRAINT fk_pagamento_hospede
    FOREIGN KEY (hospede_id)
    REFERENCES hotel.hospede
);
